kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: event-listener-role
rules:
- apiGroups:
  - triggers.tekton.dev
  resources:
  - eventlisteners
  - triggers
  - triggerbindings
  - triggertemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: event-listener-role-binding
subjects:
  - kind: ServiceAccount
    name: event-listener
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: event-listener-role
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: event-listener-cluster-role
rules:
- apiGroups:
  - triggers.tekton.dev
  resources:
  - clusterinterceptors
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-listener-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: event-listener
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: event-listener-cluster-role
